language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g mocha chai codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

cache:
  - npm
