version: 0.2

phases:
  install:
    commands:
      - echo Installing gulp...
      - npm install -g gulp-cli gulp gulp-debug gulp-zip
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - echo npm version...
      - npm version prerelease -m "CI BUILD"
  build:
    commands:
      - echo Build started on `date`
      - gulp
  post_build:
    commands:
      - echo Build completed on `date`
      - git push --follow-tags
artifacts:
  files:
    - dist/*.zip