version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing gulp...
      - npm install -g gulp-cli@2.0.0 gulp@4.0.0 gulp-debug@4.0.0 gulp-zip@4.2.0
      - echo Installing dependencies...
      - npm install --production
  build:
    commands:
      - echo Build started on `date`
      - gulp
  post_build:
    commands:
      - echo Build completed on `date`
      - git push origin HEAD:master --follow-tags
artifacts:
  files:
    - dist/*.zip