version: 0.2

phases:
  install:
    commands:
      - echo setup git...
      - git config --global user.email "ci@email.com"
      - git config --global user.name "Continuous Integration"
  pre_build:
    commands:
      - echo npm version...
      - npm version prerelease -m "CI BUILD"
      - echo Installing gulp...
      - npm install -g gulp-cli@2.0.0 gulp@4.0.0 gulp-debug@4.0.0 gulp-zip@4.2.0
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - gulp
  post_build:
    commands:
      - echo Build completed on `date`
      - git push HEAD:master --follow-tags
artifacts:
  files:
    - dist/*.zip