version: 0.2

phases:
  install:
    commands:
      - echo Installing gulp...
      - npm install -g gulp-cli gulp
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - gulp
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/*.zip